<?
	$this->full_width = true;
	$bc = $this->breadcrumb()->prepend(Link::home()->a(__("Accueil"))); 
	$bc->append("Rejoignez-nous");
	$this->headTitle("Rejoignez-nous");
	$this->headMeta()
		->appendName("description", "Rejoignez-nous");

?>
<!-- SERP CONTAINER -->
<div class="container-fluid launching">
	<div class="launching_container center-block">
		<h1>Tatoueurs, Rejoignez-nous !</h1>
		<?= $this->formHeader($this->form) ?>
		<? if(!$this->contacted): ?>
		<?= $this->form->hideLabels(true)
			->renderGroups(array(
				"fname"=>__("Prénom"),
				"lname"=>__("Nom"),
				"email"=>__("Email"),
				"number"=>__("Téléphone")
		)); ?>
			<button type="submit" class="btn btn-default" style="margin-left:0;">S'inscrire !</button>
			<? endif ?>
		</form>
	</div>
</div>
<!-- FIN SERP CONTAINER -->
<?= $this->partial("shared/_remarketing.phtml") ?>
