<?
	$this->full_width = true;
	$bc = $this->breadcrumb()->prepend(Link::home()->a(__("Accueil"))); 
	$bc->append("Créations");
	$this->headTitle("Créations de tatouages");
	$this->headMeta()
		->appendName("description", "Créations de tatouages");

?>

<? $this->partial("shared/_sub-header.phtml", $this) ?>		<!-- SERP CONTAINER -->
		<div class="container-fluid launching">
			<div class="launching_container center-block">
				<h1>Ici, Bientôt...</h1>
				<p>Vous pourrez créer votre motif avec un artiste.</p>
				<p>Soyez informé en avant première, laissez votre email :</p>
				<?= $this->formHeader($this->form, array("class"=>"form-inline")) ?>
				<? if($this->contacted == false): ?>
				<? $this->form->hideLabels(true); ?>
					<?= $this->form->renderGroups(array(
								"email"=>array(
									"group_class"=>"launch_email",
									"label"=>__("Adresse email")
								)))
					?>
					<button type="submit" class="btn btn-default">S'inscrire !</button>
				<? endif ?>
				</form>
			</div>
			
		</div>
		<!-- FIN SERP CONTAINER -->
		