<?
	$this->full_width = true;
	$bc = $this->breadcrumb()->prepend(Link::home()->a(__("Accueil"))); 
	$bc->append("Créations");
	$this->headTitle("Créations de tatouages");
	$this->headMeta()
		->appendName("description", "Créations de tatouages");

?>

<? $this->partial("shared/_sub-header.phtml", $this) ?>		<!-- SERP CONTAINER -->
		<div class="container-fluid launching">
			<div class="launching_container center-block">
				<h1><?= __("Ici, Bientôt...") ?></h1>
				<p><?= __("Vous pourrez créer votre motif avec un artiste.") ?></p>
				<p><?= __("Soyez informé en avant première, laissez votre email :") ?></p>
				<?= $this->formHeader($this->form, array("class"=>"form-inline")) ?>
				<? if($this->contacted == false): ?>
				<? $this->form->hideLabels(true); ?>
					<?= $this->form->renderGroups(array(
								"email"=>array(
									"group_class"=>"launch_email",
									"label"=>__("Adresse email")
								)))
					?>
					<button type="submit" class="btn btn-default"><?= __("S'inscrire !") ?></button>
				<? endif ?>
				</form>
				<br><br>
				<p><?= __("Vous êtes beta-testeur ?") ?></p>
				<p><?= __("Entrez votre mot de passe pour accèder à l'espace création.") ?></p>
				<form name="creation" method="POST" action="" class="form-inline">
					<div class="form-group launch_email">
						<label class="sr-only" for="email"><?= __("Mot de passe") ?></label>
						<input type="password" name="password" id="password" value="" class=" form-control">
					</div>					
					<button type="submit" class="btn btn-default"><?= __("Valider") ?></button>
				</form>
			</div>
		</div>
		<!-- FIN SERP CONTAINER -->
		