
<? $this->placeholder('top')->captureStart() ?>
  <div id="carousel-example-generic" class="carousel slide">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <img src="http://placehold.it/1400x630" alt="Lorem ipsum">
        <div class="carousel-caption">
          <h3>Lorem est ipsum !</h3>
          <p>Vestibulum facilisis dignissim urna, eu accumsan dui viverra id. Integer euismod magna aliquam magna imperdiet, nec tristique arcu bibendum</p>
        </div>
      </div>
      <div class="item">
        <img src="http://placehold.it/1400x630" alt="Lorem ipsum">
        <div class="carousel-caption">
          <h3>Lorem not ipsum !</h3>
          <p>Nunc vitae nisl ut mi tempor laoreet. In sit amet diam id mauris adipiscing pulvinar. Vivamus porttitor tristique risus, vel fringilla mauris vulputate quis. </p>
        </div>
      </div>
      <div class="item">
        <img src="http://placehold.it/1400x630" alt="Lorem ipsum">
        <div class="carousel-caption">
          <h3>Esta no !</h3>
          <p>Nunc vitae nisl ut mi tempor laoreet. In sit amet diam id mauris adipiscing pulvinar. Vivamus porttitor tristique risus, vel fringilla mauris vulputate quis. </p>
        </div>
      </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
      <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
      <span class="icon-next"></span>
    </a>
  </div>
<? $this->placeholder('top')->captureEnd() ?>

<? $this->placeholder('sidebar')->captureStart() ?>
  <?= $this->partial('shared/_sidebar_owner_subscribe.phtml') ?>
  <? for($i = 0; $i < 3; ++$i): ?>
    <?= $this->partial('shared/_sidebar_link_list.phtml') ?>
  <? endfor ?>
<? $this->placeholder('sidebar')->captureEnd() ?>

<h2>Heading</h2>
<div class="row">
  <? for($i = 0; $i < 6; ++$i): ?>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <a href="/organizations/show">
          <img src="http://placehold.it/328x227" class="img-responsive" alt="...">
        </a>
        <div class="caption">
          <h3>Thumbnail label</h3>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
          </div>
      </div>
    </div>
  <? endfor ?>
</div>
