<? 
	$r_loc = $this->country; 
	$this->full_width = true;
	$this->body_class = "index"
?>

		<div class="container-fluid" id="banner">
			<div id="video_container">
				<video width="100%" height="auto" autoplay loop>
	  				<source src="/tattoome/video/mp4/tatoome.mp4" type="video/mp4" />
	  				<source src="/tattoome/video/ogv/tatoome.ogv" type="video/ogg" />
				</video>
			</div>
			<h1 class="banner_title gothamblack"><?= __("trouvez votre futur tatoueur") ?></h1>
			<p class="banner_subtitle gothambold"><?= __("La plus grande sélection de tatoueurs prêts à vous accueillir") ?></p>
			<? $this->search_form->getElement("search_loc_id")->setValue($r_loc->id); ?>


			<?= $this->formHeader($this->search_form, array("class"=>"banner_form form-inline")) ?>
				<p><?= __("Tatoueurs à ")?>
					<? foreach($this->country->getCities(8, "population DESC") as $r_city): ?>
						<?= $r_city->link()->a() ?>,
					<? endforeach ?>...
				</p>
				<?= $this->search_form->renderGroups(array(
				  "loc_name"=>array(
				    "label"=>__("Région, département, ville..."),
				  ),
				  "tattoo_style"=>array(
				  	"label"=>__("Tous les styles"),
				  	"group_class"=>"hidden-xs")));?>
					<button type="submit" class="btn btn-purple"><span class="hidden-xs"><?= __("RECHERCHER") ?></span><span class="visible-xs glyphicon glyphicon-search"></span></button>
			</form>
		</div>
		<!-- END FORMULAIRE TROUVER TATOUEUR -->

		<!-- BANNIERE PROMO -->
		<? if($r_loc->local_id != "ES"): ?>
		<div class="container-fluid" id="banner_promo_container">
			<div class="row" id="banner_promo">
				<div class="col-lg-4">
					<div class="promo_container_ld promo_container_left autopromo">
						<div class="title_promo">
							<h2 class="gothamblack"><?= __("Création") ?></h2>
							<p class="gothambold"><?= __("Créez votre tatouage avec un artiste dessinateur") ?></p>
						</div>
						<div class="link_promo">
							<a href="https://www.tattoome.com/creation" class="btn-link-promo link-promo-red gothambold">
								<span class="hidden-xs"><?= __("Je crée mon tatouage") ?></span>
								<span class="visible-xs"><?= __("Créer") ?></span>
							</a>
						</div>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="promo_container_ld promo_container_center autopromo">
						<div class="title_promo">
							<h2 class="gothamblack"><?= __("Tattoobox") ?></h2>
							<p class="gothambold"><?= __("Un cadeau inoubliable : offrez un tatouage") ?></p>
						</div>
						<div class="link_promo">
							<a href="https://www.tattoome.com/tattoobox" class="btn-link-promo link-promo-lightgreen gothambold"><span class="hidden-xs"><?= __("Je choisis ma tattoobox") ?></span>
							<span class="visible-xs"><?= __("Choisir") ?></span></a>
						</div>
					</div>
				</div>
                <div class="col-lg-4">
                    <div class="promo_container_ld promo_container_right autopromo">
                        <div class="title_promo">
                            <h2 class="gothamblack"><?= __("Le conseiller") ?> <span style="color:black;">Tattoo</span>Me</h2>
                            <p class="gothambold"><?= __("Un projet de tatouage") ?> ?</p>
                            <p class="gotham"><?= __("Notre conseiller sélectionne pour vous les meilleurs tatoueurs") ?></p>
                        </div>
                        <div class="link_promo">
                            <a href="<?=  $this->link(array(), 'conciergerie')?>" class="btn-link-promo link-promo-lightgreen gothambold"><span class="hidden-xs"><?= __("Je prends contact") ?></span>
                            <span class="visible-xs"><?= __("Contact") ?></span></a>
                        </div>
                    </div>
                </div>				
			</div>
		</div>
		<!-- FIN BANNIERE PROMO -->
		<!-- BANNIERE PROMO 2-->
		<div class="container-fluid" id="banner_promo_container">
			<div class="row promo_container_md blog-banner-promo" id="banner_promo">
				<div class="col-lg-9" id="blog_preview"></div>
					<div class="col-lg-3 promo_container_md_singleton promo_container_md_singleton_right promo_container_md_singleton_custom">
						<p class="francoisone label_tag"><?= __("Newsletter") ?></p>								
						<h2 class="custom_title_text_prom gothamblack"><?= __("News,<br/>Bons plans, Tendances...")?></h2>
						<p class="custom_text_prom gothambook"><?= __("Recevez le meilleur du tatouage par email") ?></p>
						<a href="#" class="btn-custom-link-promo link-promo-violet gothambook"><?= __("Je m'inscris") ?></a>
					</div>
			</div>
		</div>
		<!-- FIN BANNIERE PROMO 2-->
		<? else: ?>
		<div class="container-fluid" id="banner_promo_container">
			<div class="row promo_container_md" id="banner_promo">
        <div class="col-lg-6 adviser">
            <div class="promo_container_ld promo_container_right autopromo">
                <div class="title_promo">
                    <h2 class="gothamblack"><?= __("Le conseiller") ?> <span style="color:black;">Tattoo</span>Me</h2>
                    <p class="gothambold"><?= __("Un projet de tatouage") ?> ?</p>
                    <p class="gotham"><?= __("Notre conseiller sélectionne pour vous les meilleurs tatoueurs") ?></p>
                </div>
                <div class="link_promo">
                    <a href="<?=  $this->link(array(), 'conciergerie')?>" class="btn-link-promo link-promo-lightgreen gothambold"><span class="hidden-xs"><?= __("Je prends contact") ?></span>
                    <span class="visible-xs"><?= __("Contact") ?></span></a>
                </div>
            </div>
        </div>
        
				<div class="col-lg-6 newsletter">
					<div class="promo_container_md_singleton promo_container_md_singleton_right promo_container_md_singleton_custom">
						<p class="francoisone label_tag"><?= __("Newsletter") ?></p>								
						<h2 class="custom_title_text_prom gothamblack"><?= __("News,<br/>Bons plans, Tendances...")?></h2>
						<p class="custom_text_prom gothambook"><?= __("Recevez le meilleur du tatouage par email") ?></p>
						<a href="#" class="btn-custom-link-promo link-promo-violet gothambook"><?= __("Je m'inscris") ?></a>
					</div>
				</div>
			</div>
		</div>
		<? endif; ?>
		<script>
    		$(document).ready(function(){
    		     $('.promo_container_md_singleton_right').on('click',function(e){
    		          $('.lightbox').show(); 
    		          e.stopPropagation();  
    		     });
    		});
			$(function(){
				$("#blog_preview").load('https://www.tattoome.com/blog/ .top_slider_blog .stand_slide:nth-child(-n+3)');
			});
		</script>

		<!-- SECTION 1 ( STYLE ) -->
		<section class="container-fluid section hidden-xs">
			<div class="row section-style" id="section_content">
				<div class="row no-margin">
					<div class="section_header">
						<h3 class="francoisone"><?= __("les styles de tatouage") ?></h3>
						<p><?= __("Découvrez les meilleurs tatouages par style") ?></p>
					</div>
				</div>
				<div class="row section_container" style="margin-left:0px;">
					<? foreach(App::table("attributes")->tattooStyle() as $r_attr):?>
					<? $link = $r_loc->linkGalery("attr:".$r_attr->id, "galery-with-filters"); ?>
								<div class="sm_img_container">
									<? 
										$img = $r_attr->firstImage();
										$url = isset($img) ? $img->url("small") : "http://placehold.it/173x177";
									?>
									<?= $link->jslink("<img src='$url' class='img-responsive' width='150' height='150'/>"); ?>
									<p class="label_sm_img">
									<?= $link->a(__("Tatouage :style:", array("style"=>$r_attr->name())), "text-white"); ?>
									</p>
								</div>
					<? endforeach ?>
				</div>
			</div>
		</section>
		<!-- FIN SECTION 1 ( STYLE ) -->
		<!-- SECTION 2 ( STUDIO ) -->
		<section class="container-fluid section">
			<div class="row" id="section_content">
				<div class="section_header">
					<h3 class="francoisone"><?= __("Les Studios de tatouage près de chez vous") ?></h3>
					<p><?= __("Choisissez votre studio par situation géographique") ?></p>
				</div>
				<div class="section_container_region">
					<div class="row">
						<ul class="col-md-3">
							<? $children = $r_loc->getChildren(); ?>
							<? $columnize = $this->columnize($children->count(), 3, '</ul><ul class="col-md-3">');?>
							<? foreach($children as $row): ?>
								<li><p><?= $row->link()->a(__("Les tatoueurs en :region:", array("region"=>$row->name())), "text-black")?></p></li>
								<?= $columnize ?>
							<? endforeach ?>
							</ul>
							<ul class="col-md-3">
								<? foreach($r_loc->getCities(8, "population DESC") as $r_city): ?>
									<li><p><?= $r_city->link()->a(__("Tatoueurs à :name:", array("name"=>$r_city->name())), "text-black")?></p></li>
								<? endforeach; ?>
							</ul>
					</div>	
				</div>
			</div>
		</section>
		<!-- FIN SECTION 2 ( STUDIO ) -->

		<!-- SECTION 3 ( PUB ) -->
		<section class="container-fluid section">
			<div id="section_content" class="row no-border">
				<div class="section_header">
					<h3 class="francoisone"><?= __("Ils parlent de nous") ?></h3>
				</div>
				<div class="section_container_logo">
					<div class="row">
						<div class="col-lg-3">
							<img src="/img/home_biba.png" alt="" class="img-responsive center-block">
						</div>
						<div class="col-lg-3">
							<img src="/img/home_grazia.png" alt="" class="img-responsive center-block">
						</div>
						<div class="col-lg-3">
							<img src="/img/home_shweppes.png" alt="" class="img-responsive center-block">
						</div>
						<div class="col-lg-3">
							<img src="/img/home_inkage.png" alt="" class="img-responsive center-block">
						</div>
					</div>
				</div>
			</div>
		</section>
		<!-- FIN SECTION 3 ( PUB ) -->
		<?	$this->headTitle(__("Galerie du tatouage devient Tattoome"), "SET"); ?>


	<?= $this->partial("shared/_mailing-dialog.phtml") ?>
