<?

?>
<?= __('Bonjour :who:', array('who' => $this->recipient->fname)) ?>,
<br/>
<br/>
Un de vos proche ou vous-même parlez régulièrement de votre futur tatouage?
Pourquoi ne pas lui (vous) l'offrir?
<br/>
<br/>
TattooMe a récemment lancé la TattooBox, le chêque cadeau valable dans près de 200 studios de tatouage triés sur le volet et situés dans toute la France.
<br/>
<br/>
Pour découvrir la Tattoobox c'est par ici: <a href="https://www.tattoome.com/tattoobox/">https://www.tattoome.com/tattoobox/</a>
<br/>
<br/>
N'hésitez plus!
<br/>
L'équipe TattooMe