<div class="well">
  A partir de <br>
  <strong>175€ <small>par nuit</small></strong>
  
  <h3>Réservez votre séjour !</h3>
  <h4>Par téléphone</h4>
  <a href="javascript: void(0)" class="btn btn-default btn-block" id="book-by-phone">Réservez par téléphone</a>
  <ol id="book-by-phone-content" class="list-unstyled" style="display: none">
    <li>
      <h4 class="h3">Etape 1</h4>
      Composez le numéro de téléphone suivant : <br>
      <strong>0670 458 469</strong>
    </li>
    <li>
      <h4 class="h3">Etape 2</h4>
      Composez le code suivant qui est le code de la propriété que vous avez choisi de réserver : <br>
      <strong>0670 458 469</strong>
    </li>
  </ol>
  
  <h4>Par e-mail</h4>
  <p>Pour contacter le propriétaire par e-mail, remplissez ce formulaire</p>
  
  <form class="form-horizontal" role="form">
    <div class="form-group">
      <label for="checkin_date" class="col-md-4 control-label">Arrivée</label>
      <div class="col-md-8">
        <input type="date" class="form-control input-sm" id="checkin_date" placeholder="<?= date('d/m/Y') ?>">
      </div>
    </div>
    <div class="form-group">
      <label for="checkout_date" class="col-md-4 control-label">Départ</label>
      <div class="col-md-8">
        <input type="date" class="form-control input-sm" id="checkout_date" placeholder="<?= date('d/m/Y') ?>">
      </div>
    </div>
    <div class="form-group">
      <label for="nb_persons" class="col-md-4 control-label">Voyageurs</label>
      <div class="col-md-8">
        <input type="numeric" class="form-control input-sm" id="nb_persons">
      </div>
    </div>
    <div class="form-group">
      <label for="name" class="col-md-4 control-label">Nom</label>
      <div class="col-md-8">
        <input type="text" class="form-control input-sm" id="name">
      </div>
    </div>
    <div class="form-group">
      <label for="email" class="col-md-4 control-label">E-mail</label>
      <div class="col-md-8">
        <input type="email" class="form-control input-sm" id="email">
      </div>
    </div>
    <div class="form-group">
      <label for="tel" class="col-md-4 control-label">Téléphone</label>
      <div class="col-md-8">
        <input type="text" class="form-control input-sm" id="tel">
      </div>
    </div>
    <p>Pour être assuré d'être recontacté par le propriétaire, spécifiez votre numéro de téléphone.</p>
    <textarea class="form-control" rows="3"></textarea>
    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <div class="checkbox">
          <label>
           <input type="checkbox"> Recevoir les promotions des partenaires de BnbAvenue  
          </label>
        </div>
      </div>
    </div>
    <button type="submit" class="btn btn-default btn-block">Envoyer</button>
  </form>
</div>
