<?
$col = !empty($this->col) ? $this->col : 3;
$r_img = $this->img;
$size = !empty($this->size) ? $this->size : "small";
$modal = empty($this->modal) && $this->modal == true ? 'data-toggle="modal" data-href="'.$url.'"' : '';
$meta = empty($this->meta) ? false : $this->meta;
?>

<? $url = $this->link(array("id"=>$r_img->id),"galery-focus")->option("canonical", true)->assemble()?>
<div class="col-md-<?= $col ?>" style="padding-right:0px">
	<a href="<?= $url ?>"' class="show-focus thumbnail" >
		<img src="<?= $r_img->url($size) ?>" alt="gallery" class=""/>
			<? if(!isset($this->hide_buttons)): ?>
			<div class="text-center" style="margin-top:4px">    	
			<div class="fb-like" data-href="<?= $url?>" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
			</div>
			<? endif ?>
			<? if($meta): ?>
				<p class="text-center caption"><?= strip_tags($r_img->meta());?></p>
			<? endif ?>
	</a>
</div>
