<?
	$this->active = "conventions";
	$this->full_width = true;
	$bc = $this->breadcrumb()->prepend(Link::home()->a(__("Accueil"))); 
	$bc->append(__("Conventions"));
	$this->headTitle(__("Conventions de tatouages"));
	$this->headMeta()
		->appendName("description", __("Conventions de tatouages"));

?>

<? $this->partial("shared/_sub-header.phtml", $this) ?>
		<!-- SERP CONTAINER -->
		<div class="container-fluid launching">
			<div class="launching_container center-block">
				<h1><?= __("Ici, Bientôt...")?></h1>
				<p><?= __("Nous vous proposerons notre sélection des rendez-vous tatouage à ne pas manquer: conventions, salons, ateliers...")?></p>
				<p><?= __("Soyez informé en avant première, laissez votre email :") ?></p>
				<?= $this->formHeader($this->form, array("class"=>"form-inline")) ?>
				<? if($this->contacted == false): ?>
				<? $this->form->hideLabels(true); ?>
					<?= $this->form->renderGroups(array(
								"email"=>array(
									"group_class"=>"launch_email",
									"label"=>__("Adresse email")
								)))
					?>
					<button type="submit" class="btn btn-default"><?= __("S'inscrire !") ?></button>
				<? endif ?>
				</form>
			</div>
			
		</div>
		<!-- FIN SERP CONTAINER -->