<?
	$this->full_width = true;
	$this->active = "galery";
?>

<?
	$have_filter = (isset($this->current_filters["attr"]) && count($this->current_filters["attr"]) >= 1);
	$noindex = (isset($this->current_filters["attr"]) && count($this->current_filters["attr"]) > 1);
	
	if($noindex) $this->headMeta()->appendName("robots", "noindex,follow");
?>
<? $this->body_class = "galery" ?>
<? $this->placeholder('sidebar')->captureStart() ?>
<? $this->placeholder('sidebar')->captureEnd() ?>

<? $focus = !empty($this->img); ?>
<?
  $page = $this->images->getCurrentPageNumber();
  $bc = $this->breadcrumb(); 
  $bc = $this->breadcrumb()->prepend(Link::home()->a(__("Accueil"))); 
  $bc->append("Idée tatouages");
  
?>
<? $this->placeholder("h1")->captureStart() ?>
<? 
	$page_label = "";
	$attr_names = $this->filtersLabel();

	if(!empty($attr_names) || $page >1){
		$page_label = " - ";
	}
	$page_label .= $attr_names;
	if($page > 1){
		$page_label.= " - ".__("page :num:", array("num"=>$page));
	}
	
	if(count($this->current_styles) == 1){
		$r_attr = current($this->current_styles);
	} 
?>
<? $this->partial("shared/_sub-header.phtml", $this) ?>

	<? 
		$style = !empty($attr_names) ? " $attr_names" : "";
		$meta_desc = __("Retrouvez les meilleurs tatouages:style: notés par les internautes. Et trouvez des idées pour votre prochain tatouage.", array("style"=>$style));
			
		if($page > 1){
			$meta_desc .= " - page $page";
			$head_title = __("Les meilleurs tatouages:style: - page $page", array("style"=>$style));
			$h1 = __("Les <b>tatouages</b> de la galerie");
		} else {
			$head_title = __("Idées tatouages:style:", array("style"=>$style));
			$h1 = __("Idées <b>tatouages:style:</b>", array("style"=>$style));
			$page_label = "";
		}
		
		if(isset($r_attr) && $page == 1){
			$meta = $r_attr->metaDescription();
			$meta_desc = !empty($meta) ? $meta : $meta_desc;
			
			$title = $r_attr->title();
			$head_title = !empty($title) ? $title : $head_title;
		}
		
		$this->headTitle($head_title);
		$this->headMeta()
			->appendName("description", $meta_desc);
		$this->headScript()->prependFile("/js/search-utils.js");
	?>
<!-- FOR search-utils.js -->
<script>
var num_page = <?= $this->images->count()?>;
var current_page = <?= $page?>;
var baselink = '<?= $this->baselink ?>';
</script>

		<!-- SERP CONTAINER -->
		<div class="container-fluid serp idees">
			<div class="serp_container center-block">
				<!-- content -->
				<div class="row serp_main">
					<!-- left panel -->
					<div class="col-lg-3">
						<div class="filtres">
							<p class="filtres_title">
								Filtrer par style
							</p>
							<div class="hidden-xs">
							<? foreach($this->filters as $link): ?>
								<div class="checkbox">
					        <label>
    									<? $link->option("jslink", $have_filter	); ?>
					            <input type="checkbox"> <?= $link->a()?>
					        </label>
						    </div>
							<? endforeach ?>
							</div>
							<form>
								<select name="style" class="style form-control visible-xs">
								<? 
									$url = $this->link(array(), "galery")->assemble();
									$current = $this->current_url;
								?>
								<option value="<?= $this->link(array(), "galery")->assemble() ?>" <?= $url == $current ? "selected":""?> >Tous les tatouages</option>
								<? foreach($this->filters_select as $url=>$label): ?>
									<option value="<?= $url ?>" <?= $url == $current ? "selected":""?>><?= $label ?></option>
								<? endforeach ?>
								</select>
							</form>
						</div>
						<?= $this->partial("shared/_sidebar-content.phtml") ?>
						<div class="filtres filtres_region">
							<?= $this->linkList()->title(__("Recherches populaires"), "h4")->labelName("tatoueurs :name:")->rs($this->adm2); ?>
						</div>
					</div>
					<!-- fin left panel -->
					<!-- resultat -->
					<div class="col-lg-9 idee_content">
						<h1 class="h2 serp_content_header_idee"><?= $h1 ?><small><?= $page_label?>
						<? if($this->user()->admin() && isset($r_attr)): ?>
								- <?= $this->link(array("table"=>"attributes","id"=>$r_attr->id), "admin/entity")->a("Editer") ?>
							<? endif ?>
					
						</small></h1>
						<? if(isset($r_attr) && $page == 1): ?>
						<div class="loc-description">
						 	<?= $this->partial("shared/description.phtml", array("row"=>$r_attr)) ?>
					 	</div>
					 	<? endif ?>

						<div>
				    <? foreach($this->images as $r_img): ?>
				    	<?= $this->partial("location/galery-item.phtml", array("img"=>$r_img)); ?>
				    <? endforeach; ?>
				    </div>
				    <div class="next-page"></div>
						<? if($this->images->count() > $page): ?>
						<h4 class="separator"><a href="" class="page-loader">voir la suite</a></h4>
						<? endif ?>
					</div>
					<!--fin resultat -->
				</div>
				<!-- fin content -->
			</div>
		</div>
		<!-- FIN SERP CONTAINER -->
		<script>
	  $("select.style").change(function(val){
		  window.location = $(this).val();
	  });
		</script>
<div style="height:200px;">&nbsp;</div>
	<div class="modal fade" id="focus-container" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    	<? if($focus): ?>
    		<?= $this->partial("location/galery-focus.phtml", array("img"=>$this->img, "form"=>$this->form)); ?>
    	<? endif ?>
    </div>
  </div>
  <? if($focus):?>
  <script>
	  $('#focus-container').modal();
	</script>
	<?
	  $this->doctype(Zend_View_Helper_Doctype::XHTML1_RDFA);
	  $this->headMeta()->appendProperty("og:title", $this->img->name()." - La galerie du tatouage");
	  $this->headMeta()->appendProperty("og:description", strip_tags($this->img->meta()));
	  $this->headMeta()->appendProperty("og:image", "http://".App::config()->link->domain.$this->img->url("orig"));
		$this->headMeta()->appendProperty("og:type", "website");
	  $this->headMeta()->appendProperty("og:url", $this->link(array("id"=>$this->img->id),"galery-focus")->option("canonical", true)->assemble());
	  $this->headMeta()->setName("description",  $this->img->name());
	  $this->headTitle()->set($this->img->name()." - ".$this->img->organization()->name());
	 ?>
  <? endif ?>
</div>
<script>
function init_show_focus(){
	$("#focus-container .modal-content").load(this.href, function(){
		$('#focus-container').modal();
    FB.XFBML.parse(); 
	});
	return false;
}
function on_serp_page_loaded(){
	$(".show-focus").click(init_show_focus);
}
$(".show-focus").click(init_show_focus);

</script>
