<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h4 class="modal-title" id="myModalLabel"><?= $this->img->name() ?>
  	<?
		$caption = $this->img->meta();
	?>
	<small><?=$caption?></small>
  </h4>
  
</div>
<div class="modal-body galery-focus">
	<div class="thumbnail">
		<img class="img-responsive" src="<?= $this->img->url("orig")?>"/>
	</div>
	<div>
		<?= __("Ce tatouage vous plait, cliquez sur j'aime et partagez-le sur facebook");?>
    <? $url = $this->link(array("id"=>$this->img->id),"galery-focus")->option("canonical", true)->assemble()?>
    <br/>
    <div class="fb-share-button" data-type="button" href="<?= $url ?>" data-href="<?= $url ?>"></div>
		<div class="fb-like" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false" data-href="<?= $url?>"></div>
	</div>
</div>

<? $this->headMeta()->appendName("robots", "noindex,follow"); ?>