<?
  $free = array();
  $page = $this->ads->getCurrentPageNumber();
 	$this->active = "studio";
  $bc = $this->breadcrumb()->setLoc($this->location)->prepend(App::table("locations")->linkHomeCountry($this->country)->a(__("Accueil"))); 
  if($page > 1){
    $bc->append(__("Page :num:", array("num"=>$page)));
  }
  $loc_desc = $this->location->description();
  $this->full_width = true;
  $country = $this->country;

  $this->belgium = $country->local_id == "BE";
    if(!$this->location->indexed || !in_array(App::lang(), $this->location->langs())){
        $this->headMeta()
            ->appendName("robots", "noindex, nofollow");
    }
?>

<? 
	$page_label = "";
	$attr_names = $this->filtersLabel();

	if($page >1){
		$page_label = " - ";
	}
	$page_label .= $attr_names;
	if($page > 1){
		$page_label.= " ".__("page :num:", array("num"=>$page));
	}
?>

<? 
	$loc_name = $this->location->name();
	$style = !empty($attr_names) ? __(' style :style:', array("style"=>$attr_names)) : "";
	$meta_desc = __("Retrouvez les meilleurs tatoueurs de :name::style:. Regardez et évaluez leur travail. Découvrez les évaluations des studios de tatouage faites par les internautes.", array("style"=>$style, "name"=>$loc_name));
			
	$page_title = __("Tatoueur:style: :name:", array("style"=>$style, "name"=>$loc_name));
		
	if($page > 1){
		$meta_desc .= " - page $page";
		$page_title.= " - page $page";
	}
	
	if(empty($attr_names) && $page == 1){
		$meta = $this->location->metaDescription();
		$meta_desc = !empty($meta) ? $meta : $meta_desc;
		
		$title = $this->location->title();
		$page_title = !empty($title) ? $title : $page_title;
	}
	
	$this->headTitle($page_title);
	$this->headMeta()
		->appendName("description", $meta_desc);
	$this->headScript()->appendFile("/js/search-utils.js");
?>
<!-- FOR search-utils.js -->
<script>
var num_page = <?= $this->ads->count()?>;
var current_page = <?= $page?>;
var baselink = '<?= $this->baselink ?>';
function on_serp_page_loaded(){
 	$('input[type=radio].star').rating();
}
</script>

		<!-- FORMULAIRE TROUVER TATOUEUR -->
		<div class="container-fluid" id="form_trouver_tatoueur_container">
			<p class="banner_title h1 hidden-xs hidden-sm"><?= __("trouvez un tatoueur près de chez vous") ?></p>
			<? if(isset($this->search_form)):?>
			<?= $this->formHeader($this->search_form, array("class"=>'form-inline form_trouver_tatoueur center-block'))?>
					<?= $this->search_form->renderGroups(array(
					  "loc_name"=>array(
					    "group_class"=>"input_localisation"
					  )));?>
					<button type="submit" class="btn btn-purple"><span class="hidden-xs"><?= __("RECHERCHER") ?></span><span class="visible-xs glyphicon glyphicon-search"></span></button>
			</form>
			<? endif ?>
		</div>
		<!-- END FORMULAIRE TROUVER TATOUEUR -->
		<!-- BREADCRUMB -->
		<div class="container-fluid breadcrum_container">
		  <? echo $bc ?>
		</div>
		<!-- END BREADCRUMB -->

		<!-- SERP CONTAINER -->
		<div class="container-fluid serp">
			<div class="serp_container center-block">
				<!-- content -->
				<div class="row serp_main">
					<!-- left panel -->
					<div class="col-md-3 hidden-xs hidden-sm">
						<h2 class="serp_filtre_header">
							<?=__(":num: tatoueurs trouvés", array("num"=>$this->num_products))?>
						</h2>
						<div class="filtres">
							<p class="filtres_title">
								<?= __("Filtrer par style") ?>
							</p>
								<? foreach($this->filters as $key=>$filter_data): ?>
									<? foreach($filter_data["rowset"] as $r_attr):?>
								    <div class="checkbox">
								    	<label>
											<?= $this->linkFilter($this->current_filters, $r_attr, $country->local_id == "FR"); ?>
								    	</label>
								    </div>
									<? endforeach ?>
								<? endforeach ?>
						</div>
						<?= $this->partial("shared/_sidebar-content.phtml") ?>
						<div class="filtres filtres_region">
						  <?= $this->linkList()->title(__("Recherches similaires"), "h4")->labelName("tatoueurs :name:")->rs($this->brothers); ?>
						  <?= $this->linkList()->title(__("Recherches populaires"), "h4")->labelName("tatoueurs :name:")->rs($this->cities); ?>
						  <? $children = $this->linkList()->title(__("Affinez votre recherche"), "h4")->labelName("tatoueurs :name:")->rs($this->children); 
							  echo $children;
						  ?>
						  <? $this->linkList()->title(__("Ils viennent de nous rejoindre"), "h4")->labelName("tatoueurs :name:")->rs($this->lastAds); ?>
						  <?= $this->linkList()->title(__("Les villes de :name:", array("name"=>$this->location->name())), "h4")->rs($this->cities_index); ?>

						</div>
					</div>
					<!-- fin left panel -->
					<!-- resultat -->
					<div class="col-md-9">
						<h1 class="h2 serp_content_header"><?= __("Tatoueurs :loc:", array("loc"=>$this->location->inName()))?>
						<small><span class="serp_content_header_emphase"><?= $page_label ?></span>
						<? if($this->user()->admin()): ?>
							- <?= $this->link(array("table"=>"locations","id"=>$this->location->id), "admin/entity")->a("Editer") ?>
						<? endif ?>
						</small></h1>
					 	<? if($page == 1 && empty($attr_names)): ?>
					 	<div class="loc-description">
						 	<?= $this->partial("shared/description.phtml", array("row"=>$this->location)) ?>
					 	</div>
					 	<? endif ?>
						<? foreach($this->ads as $r_ad): ?>
							<?
						    $r_image = current($r_ad->firstImage());
					     	$org_name = $r_ad->meta('name');
						    $org_desc = $r_ad->meta('short_desc');
							$org_desc = !empty($org_desc) ? $org_desc : __("Ce texte n'est pas disponible dans cette langue");
						    $city_name = $r_ad->meta("city_name");
						    $city_link = $r_ad->meta("city_link");
						    $nb_image = $r_ad->meta('num_image');
						    $link = $r_ad->link();
						    $last_status = isset($status) ? $status : null;
						    $status = $r_ad->getStatus();
	 					    $first_free = isset($status) ? $last_status != $status : false;
				    ?>
				    <? if($status == 'free'): ?>

				    	<? if($first_free): ?>
    						<div class="label_free-tattoos element-singleton"><?= __("Tatoueurs non-membres")?> <img src="/img/logo_tattoome_free.png"" alt="TattooMe" /></div>
    					<? endif ?>
                <div class="resultat_singleton element-singleton">
                  <div class="container-fluid">
                      <div class="row resultat_header">
                          <div class="col-lg-8">
                              <h3><?= $link->a(null, "text-purple"); ?></h3>
                          </div>
                      </div>
                      <div class="row ">
                          <div class="col-lg-12">
                              <p><a href="<?= $city_link ?>" class="text-black"><?= __("Tatoueur a :city:", array("city"=>$city_name)) ?></a>
                                  <?= !empty($r_ad->distance) ? "(".number_format($r_ad->distance, 1)."km)":""; ?>            
                              </p>
                          </div>
                      </div>
                      <div class="row resultat_content">
                          <div class="col-lg-12">
                              <div class="resultat_content_texte resultat_content_texte_free">
                                <p><?= $org_desc ?></p>
                              </div>
                          </div>
                      </div>
                      <div class="row resultat_footer free-resultat_footer">
                          <div class="col-lg-12">
                              <div class="resultat_footer_bottom free-resultat_footer_bottom">
                                  <?= $link->a("en savoir plus", "link-promo-violet link-free-tattoos") ?>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
				    <? else: ?>
						<div class="resultat_singleton element-singleton">
							<div class="container-fluid">
								<div class="row resultat_header">
									<div class="col-lg-8">
										<h3><?= $link->a(null, "text-purple"); ?></h3>
									</div>
									<div class="col-lg-4 resultat_singleton_avis">
										<?= $link
			          		->option("fragment", "guestbook") 
			          		->a( __(":num: avis", array("num"=>$r_ad->meta("num_review"))), "text-center text-black pull-right") ?></p>
			          		<div class="pull-right">
			          			&nbsp;&nbsp;
											<?= $this->starRate("avg_rating".$r_ad->org_id, $r_ad->avg_rating);?>
			          		</div>
									</div>
								</div>
								<div class="row resultat_header_lieu">
									<div class="col-lg-12">
										<p><a href="<?= $city_link ?>" class="text-black"><?= __("Tatoueur a :city:", array("city"=>$city_name)) ?></a>
											<?= !empty($r_ad->distance) ? "(".number_format($r_ad->distance, 1)."km)":""; ?>			
										</p>
									</div>
								</div>
								<div class="row resultat_content">
									<div class="col-lg-12">
										<div class="resultat_content_image">
											<?= $this->imgTag($r_image, "small", array(
						      		"link"=>$link,
						      		"size"=>"172x172",
						      		"alt"=>"tatoueur $city_name - $org_name",
						      		"title"=>"studio tatouage $city_name - $org_name")) ?>
										</div>
										<div class="resultat_content_texte">
											<p><?= $org_desc ?></p>
												<br>
											<? if($people = $r_ad->meta("people")): ?>
											<p><?= __("TATOUEURS :") ?> <?= $people ?></p>
											<? endif ?>
												<br>
											<? if($styles = $r_ad->meta("style")): ?>
											<p><?= __("STYLES :") ?>
												<? foreach($styles as $style): ?>
													<span class="resultat_content_texte_tag"><?=$style?></span>
												<? endforeach; ?>
											</p>
											<? endif ?>
										</div>
									</div>
								</div>
								<div class="row resultat_footer">
									<div class="col-lg-12">
										<div class="resultat_footer_tatoo hidden-xs">
											<?= $link->a(__("Voir les :num: tatouages réalisés dans ce studio", array("num"=>$nb_image))) ?>
										</div>
										<div class="resultat_footer_bottom">
							        <? if($r_ad->tattoobox): ?>
											<a href="/tattoobox" class="pull-left tattoobox"><img src="/tattoome/images/tatoobox.png" alt=""></a>
											<? endif ?>
											<?= $link->a(__("en savoir plus"), "link-promo-violet") ?>
										</div>
									</div>
								</div>
							</div>
						</div>
						<? endif ?>
						<? endforeach ?>
						<? if(0 ): ?>
						<div id="free-tattoos">
						<div class="label_free-tattoos"><?= __("Tatoueurs non-membres")?> <img src="/img/logo_tattoome_free.png"" alt="TattooMe" /></div>
                        <? foreach(array() as $r_ad): ?>
                        <?
                        $r_image = current($r_ad->firstImage());
                        $org_name = $r_ad->meta('name');
                        $org_desc = $r_ad->meta('short_desc'); 
                        $city_name = $r_ad->meta("city_name");
                        $city_link = $r_ad->meta("city_link");
                        $nb_image = $r_ad->meta('num_image');
                        $link = $r_ad->link();
                        ?>

                        <div class="resultat_singleton element-singleton">
                            <div class="container-fluid">
                                <div class="row resultat_header">
                                    <div class="col-lg-8">
                                        <h3><?= $link->a(null, "text-purple"); ?></h3>
                                    </div>
                                </div>
                                <div class="row resultat_header_lieu">
                                    <div class="col-lg-12">
                                        <p><a href="<?= $city_link ?>" class="text-black"><?= __("Tatoueur a :city:", array("city"=>$city_name)) ?></a>
                                            <?= !empty($r_ad->distance) ? "(".number_format($r_ad->distance, 1)."km)":""; ?>            
                                        </p>
                                    </div>
                                </div>
                                <div class="row resultat_content">
                                    <div class="col-lg-12">
                                        <div class="resultat_content_texte">
                                        <p><?= $org_desc ?></p>
                                        </div>
                                    </div>
                                </div>
                                <div class="row resultat_footer free-resultat_footer">
                                    <div class="col-lg-12">
                                        <div class="resultat_footer_bottom free-resultat_footer_bottom">
                                            <?= $link->a(__("en savoir plus"), "link-promo-violet link-free-tattoos") ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>            
                        <? endforeach ?>  
                        <? endif ?>
						<div class="next-page"></div>
						<? if($this->ads->count() > $page): ?>
						<h4 class="separator"><a href="" class="page-loader"><?= __("voir la suite") ?></a></h4>
						<? endif ?>
					</div>
					<!--fin resultat -->
				</div>
				<!-- fin content -->
			</div>
		</div>
		<!-- FIN SERP CONTAINER -->
		