<html class="no-js" lang="fr" prefix="og: http://ogp.me/ns#">
	<head>
		<title>MUSICFLOW Template html/css</title>
			<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
			<script type="text/javascript" src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
		<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" media="" rel="stylesheet" type="text/css">
		<link href="/uop/bootstrap-lightbox/bootstrap-lightbox.css" media="screen" rel="stylesheet" type="text/css">

		<script type="text/javascript" src="/uop/bootstrap-lightbox/bootstrap-lightbox.js"></script>
		
		
	</head>
	<body id="body" class="" style="" data-pinterest-extension-installed="cr1.3.2">
<!-- Button trigger modal -->
<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

	</body>
</html>	