<!DOCTYPE html>
<html lang="<?= App::lang()?>">
	<head>
		<meta charset="UTF-8">
		<? $this->headTitle()->append("Tattoome, ex Galerie du Tatouage") ?>
		<?= $this->headTitle() ?>
		<?= $this->headMeta()?>
		<!-- JAVASCRIPTS CALL -->
		<script src="/tattoome/js/jquery-1.12.0.min.js"></script>
		<script src="/tattoome/js/bootstrap.min.js"></script>
		<!-- STYLE CALL -->
		<? $this->headLink()
			->appendStylesheet("/tattoome/css/bootstrap-custom.css")
			->appendStylesheet("/tattoome/css/style.css?".uniqid()); ?>

		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
		<link href='https://fonts.googleapis.com/css?family=Francois+One' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,300italic,700' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Lato:400,700,400italic,300italic,300,700italic' rel='stylesheet' type='text/css'>
					<!-- favicon -->
			<link rel="shortcut icon" href="/favicon.ico">
			<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

			<!--[if lt IE 9]>
					<script src="js/html5.js"></script>				
			<![endif]-->
    
   	<script type="text/javascript">
			window.baseclassename = "<?= App::config()->link->baseclassname ?>";
		</script>
		<script src="https://js.gleam.io/oi-WfLa2axq.js" async="async"></script>

		<?= $this->headLink()
			->appendStylesheet("/uop/bootstrap-select/bootstrap-select.css")
      ->appendStylesheet("/css/global.less") ?>
		    
	    <?= $this->headScript()
	  		->prependFile('/uop/js/modernizr-2.7.1-custom/modernizr.min.js')
        ->appendFile('/uop/js/encryptedlink.js')
        ->appendFile('/uop/js/helper/jquery.uopAutosuggest.js')

    //    ->appendFile('//connect.facebook.net/fr_FR/all.js#xfbml=1;')
        ->prependFile("//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js")
        ->appendFile('/uop/bootstrap-select/bootstrap-select.js')
        ->appendFile("/uop/js/jquery.autosize.min.js")
        ->appendFile('//cdnjs.cloudflare.com/ajax/libs/less.js/1.5.0/less.min.js') ?>

		<script type="text/javascript">
			$.widget.bridge('uibutton', $.ui.button);
			$.widget.bridge('uitooltip', $.ui.tooltip);
		</script>
	  <script>
      $(function(){
        $('.selectpicker').selectpicker();
				$(".checkbox-filters input[type=checkbox]").click(function(){
					document.location = $(this).parent("a").attr("href");
				});
      })
    </script>
	</head>
	<body id="body" class="<?=$this->body_class?>">
		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
		
		  ga('create', '<?= App::config()->analytics->id ?>', 'auto');
		  ga('send', 'pageview');
		
		  </script>
		  <script>(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v2.0";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>
		<!-- BEGIN NAVIGATION -->
		<!-- NAVBAR -->
		<?= $this->partial("admin/navbar.phtml"); ?>
		<nav class="navbar navbar-default">
		    <div class="container-fluid" id="container-fluid-navbar">
		    <!-- Brand and toggle get grouped for better mobile display -->
			    <div class="navbar-header">
			        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu1" aria-expanded="false">
				        <span class="sr-only">Toggle navigation</span>
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
			        </button>
			        <?= Link::home()->a('TATTOO<span style="color:white;">ME</span>', "navbar-brand opensanscondensed")?>
			    </div>

		    	<!-- Collect the nav links, forms, and other content for toggling -->
			    <div class="collapse navbar-collapse" id="menu1">
			        <ul class="nav navbar-nav">
				        <li><?= $this->link(array(), 'creations')->a(__("Création")) ?></li>
				        <li><a href="http://www.galeriedutatouage.com/tattoobox">tattoobox</a></li>
				        <li><a href="http://blog.galeriedutatouage.com">blog</a></li>
			      	</ul>
			        <ul class="nav navbar-nav navbar-right">
				        <li><a href="https://www.instagram.com/lagaleriedutatouage/" target="_blank" class="instagram_link"></a></li>
				        <li><a href="https://www.facebook.com/galeriedutatouage" target="_blank" class="facebook_link"></a></li>
			        </ul>
		    	</div><!-- /.navbar-collapse -->
		    </div><!-- /.container-fluid -->
		</nav>		
		<nav class="navbar navbar-violet">
			<div class="container-fluid" id="container-fluid-navbar">
				<p class="message_inscription francoisone hidden-xs">Tatoueurs, intégrez notre guide des meilleurs studios de France	<?= $this->link(array(), "subscription-lead")->a("inscription", "lien_inscription") ?></p>
				<p class="message_inscription francoisone visible-xs">Tatoueurs, rejoignez-nous<?= $this->link(array(), "subscription-lead")->a("inscription", "lien_inscription") ?></p>
			</div>
		</nav>
		<!-- NAVBAR 2 -->
		<nav class="navbar navbar-default navbar-sousmenu francoisone">
		    <div class="container-fluid" id="container-fluid-navbar">
		    <!-- Brand and toggle get grouped for better mobile display -->
			    <div class="navbar-header">
			        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu2" aria-expanded="false">
				        <span class="sr-only">Toggle navigation</span>
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
			        </button>
			        <?= Link::home()->a('TATTOOME <br/>
			        	<span class="navbar-brand-custom-badge">
			        		Ex Galeriedutatouage
			        	</span> 
', "navbar-brand navbar-brand-custom opensanscondensed") ?>
			    </div>

		    	<!-- Collect the nav links, forms, and other content for toggling -->
			    <div class="collapse navbar-collapse" id="menu2">
			        <ul class="nav navbar-nav">
				        <li class="<?= $this->active == 'studio' ? 'active':''?>"><?= App::table("locations")->country("FR")->link()->a('Trouver un tatoueur <span class="sr-only">(current)</span>')?></li>
				        <li class="<?= $this->active == 'galery' ? 'active':''?>"><?=  $this->link(array("page"), 'galery')->a(__("Idée tatouage"))?></li>
				        <li class="<?= $this->active == 'conventions' ? 'active':''?>"><?=  $this->link(array(), 'conventions')->a(__("Conventions"))?></li>

			      	</ul>
			        <ul class="nav navbar-nav navbar-right">
	        			<? if($this->user()->loggedUser()){
									$member_link = $this->link(array(), 'user/organizations');
								} else {
									$member_link = $this->link(array(), 'user/login');
								}?>
				        <li><?= $member_link->a("espace membre", "espacemembre opensanscondensed") ?></li>
				        <li class="dropdown">
     				        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
     				        	<?= $this->belgium ? "Belgique" : "France" ?> <span class="caret"></span></a>
				            <ul class="dropdown-menu">
					            <li><?= App::table("locations")->country($this->belgium ? "FR" : "BE")->link()->a() ?></li>
				            </ul>
			         	</li>
			        </ul>
		    	</div><!-- /.navbar-collapse -->
		    </div><!-- /.container-fluid -->
		</nav>	
		<!-- END NAVIGATION -->
		<!-- FORMULAIRE TROUVER TATOUEUR -->
		<? if($sub_header= $this->placeholder("sub-header")): ?>
		<?= $sub_header ?>
		<? endif ?>
		<? if($this->full_width):?>
			<?= $this->layout()->content ?>
		<? else: ?>
		<div class="container-fluid default-container center-block">
			<? if($this->content_with_sidebar): ?>
			<div class="row" style="margin-top:30px;">
				<div class="col-lg-3 ">
					<?= $this->placeholder("sidebar") ?>
					<?= $this->partial("shared/_sidebar-content.phtml", array("joinus"=>true)) ?>
				</div>
				<div class="col-lg-9">
					<?= $this->layout()->content ?>
				</div>
			</div>
			<? else: ?>
			<?= $this->layout()->content ?>
			<? endif ?>
		</div>
		<? endif ?>
		<!-- FOOTER -->
		<footer>
			<div class="footer_top  container-default">
				<div class="row">
					<div class="col-lg-3">
						<h4 class="footer_top_header">TATTOOME</h4>
						<?= $this->link(array(), 'creations')->a(__("Création"), "footer_top_link link_uppercase") ?>
						<a href="http://www.galeriedutatouage.com/tattoobox" class="footer_top_link link_uppercase">tattoobox</a>
				    <a href="http://blog.galeriedutatouage.com" class="footer_top_link link_uppercase">blog</a>
					</div>
					<div class="col-lg-3">
						<h4 class="footer_top_header">SUIVEZ-nous</h4>
						<a href="https://www.facebook.com/galeriedutatouage/" target="_blank" class="footer_top_link">Facebook</a>
						<a href="https://www.instagram.com/lagaleriedutatouage/" target="_blank" class="footer_top_link">instagram</a>
					</div>
					<div class="col-lg-3">
						<h4 class="footer_top_header">Je suis tatoueur</h4>
						<?= $this->link(array(), "subscription-lead")->a("Je souhaite m'inscrire", "footer_top_link") ?>
					</div>
					<div class="col-lg-3">
						<h4 class="footer_top_header">recherche</h4>	
						<? foreach(App::table("locations")->country("FR")->getCities(5) as $r_city):?>
							<?= $r_city->link()->a(__("Tatoueur à :name:", array("name"=>$r_city->name())),"footer_top_link")?>
						<? endforeach; ?>
					</div>
				</div>
			</div>
			<div class="footer_bottom container-default">
				<?= Link::factory(array("page"=>"contact"), "static")->a("Contact", "footer_bottom_link")?>
				<?= Link::factory(array("page"=>"legal"), "static")->a("Mentions légales", "footer_bottom_link")?>
				<?= Link::factory(array("page"=>"legal"), "static")->a("Conditions d'utilisation", "footer_bottom_link")?>
				<?= Link::factory(array("page"=>"legal"), "static")->a("Conditions de vente", "footer_bottom_link")?>
			</div>
		</footer>
		<!-- FIN FOOTER -->

	</body>
</html>