<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="<?= App::lang()?>" prefix="og: http://ogp.me/ns#"> <!--<![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="ie9">    <![endif]-->
		<head>
			<meta charset="utf-8">
			<title>MUSICFLOW Template html/css</title>
			<!-- Mobile viewport optimized: h5bp.com/viewport -->
			<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
			<meta name="format-detection" content="telephone=no">
			<!-- Style Sheet>
			<link rel="stylesheet" type="text/css" href="css/camera.css" media="screen">
			<link rel="stylesheet" type="text/css" href="css/prettyPhoto.css" media="screen">
			<link rel="stylesheet" type="text/css" href="css/jquery.fullwidthAudioPlayer.css" media="screen">
			<link rel="stylesheet" type="text/css" href="css/jquery.fullwidthAudioPlayer-responsive.css" media="screen">
			<link rel="stylesheet" type="text/css" href="css/style.css" media="screen"-->
			<?= $this->headMeta() ?>
			<? $this->headLink()->appendStylesheet("/theme/css/style.css")
					->appendStylesheet("/theme/css/skin/scheme1.css"); ?>

			<!-- favicon -->
			<link rel="shortcut icon" href="/favicon.ico">
			
			<!--[if lt IE 9]>
					<script src="js/html5.js"></script>				
			<![endif]-->
      
     	<script type="text/javascript">
				window.baseclassename = "<?= App::config()->link->baseclassname ?>";
			</script>

			<?= $this->headLink()
				->prependStylesheet('//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css', "")
				->appendStylesheet("/uop/bootstrap-select/bootstrap-select.css")
        ->appendStylesheet('/uop/bootstrap-lightbox/bootstrap-lightbox.css')
	      ->appendStylesheet("/css/global.less") ?>
			    
		    <!--script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
		    <script>window.jQuery.ui || document.write('<script src="/js/jquery-ui-1.10.4/jquery-ui.min.js"><\/script>')</script-->
		    <?= $this->headScript()
		  		->prependFile('/uop/js/modernizr-2.7.1-custom/modernizr.min.js')
          ->appendFile('/uop/js/encryptedlink.js')
          ->appendFile('/uop/js/jquery.lazyload.min.js')
          ->appendFile('/uop/js/helper/jquery.uopAutosuggest.js')

      //    ->appendFile('//connect.facebook.net/fr_FR/all.js#xfbml=1;')
          ->prependFile("//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js")
          ->prependFile("//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js")
          ->appendFile("//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js")
          ->appendFile('/uop/bootstrap-select/bootstrap-select.js')
          ->appendFile('//cdnjs.cloudflare.com/ajax/libs/less.js/1.5.0/less.min.js') ?>

			<script type="text/javascript">
				$.widget.bridge('uibutton', $.ui.button);
				$.widget.bridge('uitooltip', $.ui.tooltip);
			</script>
		  <script>
	      $(function(){
	        $('.selectpicker').selectpicker();
	        $("img.lazy").lazyload();
	      })
	    </script>

		</head>		
		<!-- BODY -->
		
		<body id="body" class="<?=$this->body_class?>" style="<?=$this->body_style?>">
		<div id="fb-root"></div>
		<script>(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v2.0";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>
			<div class="top-wrapper-mask clearfix">	

			<!-- HEADER -->
			<?= $this->partial("admin/navbar.phtml"); ?>
			<header class="top-wrapper small-wrapper clearfix hidden-print" style="z-index:1">
					<div class="center-wrapper">
						<div class="top-content-position">
							<div class="top-content skin-font-color3">
								<div class="top-content-up skin-border-color3">
									
									<!-- Logo  -->
								
									<span class="logo"><?= Link::home()->a("LA<b>GALERIE</b>DU<b>TATOUAGE</b>") ?>	
									<div class="fb-like" 
										data-layout="button_count" 
										data-action="like" 
										data-show-faces="true" 
										data-share="false" 
										data-href="https://www.facebook.com/galeriedutatouage?fref=ts"></div>
									</span>
									
									<!-- /Logo  -->
									
									<!-- Main menu  -->
									
									<ul class="main-menu regular">
										<li><?= Link::home()->a(__("Accueil"))?></a></li>
										<li><?= App::table("locations")->country("FR")->link()->a(__("Trouver un tatoueur"))?></a></li>
										<li><?=  $this->link(array(), 'galery')->a(__("La galerie"))?></a></li>
										<li><?= $this->link(array(), 'subscription-lead')->a(__("Rejoignez-nous"))?></li>
										<? if($this->user()->loggedUser()){
											$member_link = $this->link(array(), 'user/organizations');
										} else {
											$member_link = $this->link(array(), 'user/login');
										}?>
										<li class="dropdown">
											<? if($logged_user = $this->user()->loggedUser()):?>
											<a class="dropdown-toggle" data-toggle="dropdown" data-target=".dropdown-container" href="javascript:void();"><?= __("Mon compte") ?> <b class="caret"></b></a>
											<div class="dropdown-container" >
										  <ul class="dropdown-menu dropdown-menu-right">
										    <li><?=Link::factory(array(), 'user/edit')->a(__("Infos personnelles")); ?>
										    </li>
										    <li><?=Link::factory(array(), 'user/organizations')->a(__("Mes annonces")); ?>
										    </li>
										    <li><?=Link::factory(array(), 'user/logout')->a(__("Se déconnecter")); ?>
										    </li>										  </ul>
											</div>
										  <? else: ?>
										  <span><?= $member_link->a(__("Espace membre"))?>
										  <? endif ?>
										</li>

									</ul>
									
									<!-- /Main menu  -->
									
									<!-- Mobile menu -->
									
									<span class="mobile-button icon font-size-46px skin-color-hover1">i</span>
									<ul class="mobile-menu regular">
										<li class="skin-background-color4 skin-background-hover1"><a class="skin-font-color3" href="index.html">home</a></li>
										<li class="skin-background-color4 skin-background-hover1"><a class="skin-font-color3" href="news_list_1.html">news</a></li>
										<li class="skin-background-color4 skin-background-hover1"><a class="skin-font-color3" href="events_list_1.html">events</a></li>
										<li class="skin-background-color4 skin-background-hover1"><a class="skin-font-color3" href="gallery_list_version_1.html">gallery</a></li>
										<li class="skin-background-color4 skin-background-hover1"><a class="skin-font-color3" href="video_list_version_1.html">videos</a></li>
										<li class="skin-background-color4 skin-background-hover1"><a class="skin-font-color3" href="album_list_version_1.html">albums</a></li>
										<li class="skin-background-color4 skin-background-hover1"><a class="skin-font-color3" href="shop_home.html">shop</a></li>
										<li class="skin-background-color4 skin-background-hover1"><a class="skin-font-color3" href="contact_page.html">contact</a></li>
										<li class="skin-background-color4 skin-background-hover1"><a class="skin-font-color3" href="index.html">buy template</a></li>
									</ul>
									
									<!-- /Mobile menu  -->
									
								</div>
								<div class="top-content-down skin-border-color3">
								
									<!-- Place info  -->
								
									<div class="top-content-down-text regular">
										  <div class="hidden-xs">
	  										<span class="skin-font-color1"><?= __("Vous êtes ici:")?>	 </span>
										    <?= $this->breadcrumb()->prepend(Link::home()->a(__("Accueil"))); ?>
										  </div>
									</div>
									
									<!-- /Place info  -->
									
									<!-- Social  -->
									<? if(isset($this->search_form)):?>
									<div class="global-search">
										<?= $this->formHeader($this->search_form, array("class"=>'form-inline'))?>
												<?= $this->search_form->renderGroups(array(
												  "loc_name"=>array(
												    "label"=>__("Ville, Département...")
												  )));?>
											<button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-search"></span></button>
										</form>
									</div>
									<? endif ?>
									<!--ul class="social">
										<li class="skin-background-color1 skin-background-hover3" ><a href="#"><img src="/theme/images/social/facebook.png" alt="social"></a></li>
										<li class="skin-background-color1 skin-background-hover3" ><a href="#"><img src="/theme/images/social/twitter.png" alt="social"></a></li>
										<li class="skin-background-color1 skin-background-hover3" ><a href="#"><img src="/theme/images/social/googleplus.png" alt="social"></a></li>
										<li class="skin-background-color1 skin-background-hover3" ><a href="#"><img src="/theme/images/social/lastfm.png" alt="social"></a></li>
										<li class="skin-background-color1 skin-background-hover3" ><a href="#"><img src="/theme/images/social/dribbble.png" alt="social"></a></li>
									</ul>
									
									<!-- /Social  -->
									
								</div>
							</div>
						</div>
					  <? $title = trim($this->placeholder('h1')) ?>
					  <? if(!empty($title)): ?>
					   	<?= $title ?>
					  <? endif ?>
					</div>
				<!-- /bottom background - absolute -->
				
				
				<!-- /bottom background - absolute -->
			</header>
			
			<!-- /HEADER -->

			<div class="center-wrapper main-content-wrapper">
			
				<!-- MAIN CONTENT -->

					<!-- events -->
				
				<div class="main-content">

				  <div class="row" style="margin-top: -9px; position:relative; background:#EEE">
				    <? $sidebar = trim($this->placeholder('sidebar'))?>
				    <? $col = !empty($sidebar) ? "col-sm-8" : "col-sm-12" ?>
				    
				    <div class="<?=$col?>" style="background-color:#FFF">
				    	<?= $this->flashMessages() ?>
				      <?= $this->layout()->content ?>
				    </div>
				    <? if(!empty($sidebar)): ?>
				    <div class="col-sm-4 hidden-xs" id="sideBar">
				      <?= $sidebar?>
				    </div>
				    <? endif ?>
				  </div>
				  <div class="clearfix row" style="height:15px;background: #FFF;"></div>
				</div>
				<!-- /MAIN CONTENT -->
			</div>				
				
			<!-- BOTTOM -->
				
			<div class="bottom skin-background-color2 hidden-print">
				<div class="center-wrapper widget-bottom-contact-us skin-font-color10">
				
					<!-- Bottom widget place #1 -->
				
					<div class="one-fourth regular">
						<h2 class="skin-font-color3">Contact <span class="bold">us</span></h2>
						<p>
						Ellentesque eget mi nulla, ut ultrices enim. Etiam id erat bibendum metus tristique 
						vestibulum sit amet ac mauris. Suspendisse eget nibh lectus.
						</p>
						<ul>
							<li><span class="skin-font-color1">Address:</span> New york</li>
							<li><span class="skin-font-color1">Email:</span> info@gozawi.com</li>
							<li><span class="skin-font-color1">Phone:</span> +12 323 242 423</li>
						</ul>
					</div>
					
					<!-- Bottom widget place /#1 -->
					
					<!-- Bottom widget place #2 -->
					
					<div class="one-fourth widget-bottom-latest-posts regular">
						<h2 class="skin-font-color3">Latest <span class="bold">posts</span></h2>
						<ul>
							<li><a href="#" class="skin-font-color10 skin-color-hover1">Electronic music</a></li>
							<li><a href="#" class="skin-font-color10 skin-color-hover1">Behind the stage</a></li>
							<li><a href="#" class="skin-font-color10 skin-color-hover1">Rock party in Warsaw</a></li>
							<li><a href="#" class="skin-font-color10 skin-color-hover1">Dubstep music in Norway</a></li>
							<li><a href="#" class="skin-font-color10 skin-color-hover1">Place for new album promo</a></li>
						</ul>
					</div>
					
					<!-- Bottom widget place /#2 -->
					
					<!-- Bottom widget place #3 -->
					
					<div class="one-fourth widget-bottom-tags regular">
						<h2 class="skin-font-color3">Tag <span class="bold">cloud</span></h2>
						<a href="#" class="button-small skin-background-color1 skin-font-color3 skin-background-hover3">car show</a>
						<a href="#" class="button-small skin-background-color1 skin-font-color3 skin-background-hover3">electronic music</a>
						<a href="#" class="button-small skin-background-color1 skin-font-color3 skin-background-hover3">party</a>
						<a href="#" class="button-small skin-background-color1 skin-font-color3 skin-background-hover3">promo albums</a>
						<a href="#" class="button-small skin-background-color1 skin-font-color3 skin-background-hover3">summer rock</a>
						<a href="#" class="button-small skin-background-color1 skin-font-color3 skin-background-hover3">festival</a>
						<a href="#" class="button-small skin-background-color1 skin-font-color3 skin-background-hover3">stage</a>
						<a href="#" class="button-small skin-background-color1 skin-font-color3 skin-background-hover3">dubstep</a>
						<a href="#" class="button-small skin-background-color1 skin-font-color3 skin-background-hover3">city</a>
						<a href="#" class="button-small skin-background-color1 skin-font-color3 skin-background-hover3">tickets</a>
						<a href="#" class="button-small skin-background-color1 skin-font-color3 skin-background-hover3">concerts</a>
					</div>
					
					<!-- Bottom widget place /#3 -->
					
					<!-- Bottom widget place #4 -->
					
					<div class="one-fourth widget-bottom-flickr regular last">
						<h2 class="skin-font-color3">Flickr <span class="bold">widget</span></h2>
						<ul class="flickr"></ul>
					</div>
					
					<!-- Bottom widget place /#4 -->
					
				</div>
				
				<!-- Go top - absolute  -->
				
				<div class="go-top skin-border-color5 skin-border-hover1">
					<a href="#" onClick="ScrollTo('body')"><img src="/theme/images/go-top.png" alt="go-top"></a>
				</div>	
				
				<!-- Go top - /absolute  -->
				
			</div>
				
			<!-- /BOTTOM -->
			
			<div class="clearfix"></div>
			
			<!-- FOOTER -->
			
			<div class="footer skin-background-color11 hidden-print">
				<div class="center-wrapper skin-font-color12 regular">
					<span>© 2013 - music template for themeforest. Design & code by wtxinc</span>
					<ul>
						<li><a href="#" class="skin-font-color12 skin-color-hover1">terms of use </a> / </li>
						<li><a href="#" class="skin-font-color12 skin-color-hover1">cookies </a> / </li>
						<li><a href="#" class="skin-font-color12 skin-color-hover1">job offers </a> / </li>
						<li><a href="#" class="skin-font-color12 skin-color-hover1">contact </a></li>
					</ul>
				</div>
			</div>
			
			<!-- /FOOTER -->

			<!-- ATTACHMENTS>

			<script type="text/javascript" src="js/jquery-1.10.2.min.js"></script>
			<script type="text/javascript" src="js/jquery.migrate-1.2.1.min.js"></script>
			<script type="text/javascript" src="js/jquery.easing.1.3.js"></script>
			<script type="text/javascript" src="js/jquery.mobile.customized.min.js"></script>
			<script type="text/javascript" src="js/wait.js"></script>
			<script type="text/javascript" src="js/jquery.parallax.min.js"></script>
			<script type="text/javascript" src="js/retina.js"></script>
			<script type="text/javascript" src="js/jquery.tweet.js"></script>
			<script type="text/javascript" src="js/jquery.scrollTo.js"></script>
			<script type="text/javascript" src="js/modernizer.min.js"></script>
			<script type="text/javascript" src="js/camera.js"></script>
			<script type="text/javascript" src="js/jflickrfeed.min.js"></script>
			<script type="text/javascript" src="js/jquery.prettyPhoto.js"></script>
			<script type="text/javascript" src="js/jquery-ui.js"></script>
			
			<! Player >

			<script type="text/javascript" src="js/player/soundmanager2-nodebug-jsmin.js"></script>
			<script type="text/javascript" src="https://connect.soundcloud.com/sdk.js"></script>
			<script type="text/javascript" src="js/player/amplify.min.js"></script>
			<script type="text/javascript" src="js/player/jquery.fullwidthAudioPlayer.min.js"></script>

			<!-- Custom Js >
			
			<script type="text/javascript" src="js/custom.js"></script>

			<!-- /ATTACHMENTS -->
			</div>

		</body>	

		<!-- /BODY -->
		
</html>