<? $this->content_with_sidebar = true ?>
<?= $this->partial("organization/_edit-header.phtml", array("org"=>$this->resource, "current"=>"photos")); ?>
<?
$r_org = $this->resource;
$form = $this->form;
$col_class = $this->sort ? "col-sm-2" : "col-sm-6";
$products = App::table("products")->select()->where("org_id = ?", $r_org->id)->fetchAll(array("names"=>true));
$product_table = array();
foreach($products as $r_prod){
	$product_table[$r_prod->id] = $r_prod;
}

$class=array("class"=>"btn btn-warning navbar-btn");	

$link_edit = $this->sort ? 
       $r_org->linkEditPhotos(array("mode"=>"default"))->a(__("Modifier les informations des photos"), $class):
       $r_org->linkEditPhotos(array("mode"=>"sort"))->a(__("Modifier l'ordre des photos"), $class);


?>


<?= $this->formHeader($form, 
	array("action"=>$r_org->linkEditPhotos()),
	array("js"=>"/uop/js/helper/jquery.photoForm.js")
); ?>

<? if ($this->sort) {?>
<div class="alert alert-info"><?= __("Faites glisser les photos pour changer l'ordre d'affichage"); ?></div>
<? } ?>
	<div class="navbar navbar-default navbar-collapse">
		<?= $r_org->linkManagePhotos()->a(__("Ajouter des photos"), array(
			"class"=>"btn btn-primary navbar-btn",
		))?>
		<?= $link_edit ?>
		<? if($this->sort): ?>
		<div class="navbar-right">
    	<button type="submit" class="btn btn-success navbar-btn">Enregistrer l'ordre</button>
    </div>
    <? endif ?>
	</div>
	<ul class="row sortable-container list-unstyled photo-edit-list">
		<? $x = 0; ?>
		<? foreach($r_org->getAllImages() as $r_image) : ?>
			<? $x++ ?>
			<? //$subform->hideLabels(true); ?>
			<li class="<?= $this->sort ? "col-md-2 sortable" : "col-md-6"?>">
			<input type="hidden" name="sort[]" value="<?= $r_image->id ?>">
				<div  class="row">
					<div class="<?= !$this->sort ? "col-xs-4":"col-xs-12" ?> style="position:relative">
	        	<img src="<?= $r_image->url('small') ?>" class="img-thumbnail" style="margin-bottom:5px"/>
	        </div>
	        <? if(!$this->sort): ?>
	        <div class="col-xs-8">
	  	   	 <h4>
						<? if($r_image->ref_type == 'organizations'): ?>
							<?= __("Le studio") ?>
						<? else: ?>
							<?= isset($product_table[$r_image->ref_id]) ? $product_table[$r_image->ref_id]->name() : "" ?>
						<? endif ?>
	  	   	 </h4>
	  	   	 <h5><?= $r_image->name() ?></h5>
	  	   	 <p><small><?= implode(", ", $r_image->attributesList("tattoo_style")) ?></small></p>
	        </div>	
	        <div> 
	        <div class="buttons-container">
		        <button 
			        	data-href="<?=$r_org->linkManagePhotos()?>" 
			        	data-id="<?=$r_image->id?>"
			        	type="button" 
			        	class="btn btn-danger pull-right btn-xs delete">x</button>
			      <?= $this->link(array("image_id"=>$r_image->id, "id"=>$r_org->id), "edit-photo")->a("Modifier", "btn btn-xs btn-default link-modal") ?>
			    </div>
		      <? endif ?>
				</div>
			</li>
		<? endforeach?>
	</ul>
  <div class="clearfix">
      <button type="submit" class="btn btn-success pull-right">Enregistrer</button>
  </div>
</form>
<script>
$(function(){
	$("form").photoForm({
		"sortable":<?= $this->sort ? "true":"false" ?>
	});
});
</script>