<?
  $org = $this->org;
  $this->full_width = true;
 	$this->active = "studio";
  $this->breadcrumb()->setLoc($org->location())->prepend(Link::home()->a(__("Accueil"))); 
  $form_contact = $this->contact_form;
  $loc = $org->location();
  $this->body_class = "organization-show";
  $ad = $org->ad();
  $images = $org->getAllImages();
  $products = $org->products();
  $city = $org->city();
  $country = $city->ancester(array("country"));
  $this->belgium = $country->local_id == "BE";
  
  foreach($products as $r_product){
	  $people_names[] = $r_product->name()->__toString();
  }
  if(count($people_names)>1){
	  $last_people_name = array_pop($people_names);
	  $people_names = implode(", ", $people_names).__(" et ").$last_people_name;
    $desc = __("Depuis leur studio de :loc_name:, :names: vous montrent les :num: photos de leurs derniers tatouages", array("names"=>$people_names, "num"=>$images->count(), "loc_name"=>$city->name()));

  } else {
	  $people_names = current($people_names);
    $desc = __("Depuis son studio de :loc_name:, :names: vous montre les :num: photos de ses derniers tatouages", array("names"=>$people_names, "num"=>$images->count(), "loc_name"=>$city->name()));

  }
  
	 $this->headScript()
			->appendFile("/tattoome/js/noframework.waypoints.js")
			->appendFile("/tattoome/js/utils.js")
			->appendFile("//maps.google.com/maps/api/js?sensor=false");
								

  
  $this->doctype(Zend_View_Helper_Doctype::XHTML1_RDFA);
  $this->headMeta()->appendProperty("og:title", $org->name()." - La galerie du tatouage");
  $this->headMeta()->appendProperty("og:description", $desc);
  $this->headMeta()->appendProperty("og:image", "//".App::config()->link->domain.$images->getRow(0)->url("orig"));
  $this->headMeta()->appendProperty("og:url", $org->link()->option("canonical", true)->assemble());

  $this->headMeta()->appendName("description", $desc);
  $this->headTitle()->set($org->name());
  $this->headTitle()->append(__("Tatoueur à :name:", array("name"=>$city->name())));

?>
		<? $this->partial("shared/_sub-header.phtml", $this) ?>
		<!-- SERP CONTAINER -->
		<div class="container-fluid serp">
			<div class="serp_container center-block">
				<!-- content -->
				<div class="row studio_header">
					<div class="studio_content_width studio_content_header">
						<h1><?= $org->name()?> - <?= strtoupper($city->name())?>
							<? if($this->user()->admin()): ?>
							- <small><?= $org->linkEdit()->a("Editer") ?></small>
							<? endif ?>
						</h1>
						<p>Studio de tatouage à <?= $city->name()?></p>
					</div>
					<div class="sutdio_sidebar_width studio_sidebar_header">
						<div class="studio_sidebar_header_like">
							<div class="fb">
								<div class="fb-like" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false"></div>
							</div>
						</div>					
						<div class="studio_sidebar_header_stars">
							<p><?= $ad->meta("num_review")?> avis</p>
							<?= $this->starRate("avg_rating_main".$org->id, $ad->avg_rating);?>
						</div>
					</div>
				</div>
				<div class="row studio_content">
					<!-- content -->
					<div class="studio_content_width">
						<div class="subnav_studio" id="barre-fixe">
							<ul>
								<li><a href="#photos">Photos</a></li>
								<li><a href="#products">Tatoueurs</a></li>
								<li><a href="#location"><span class="hidden-xs">Horaires / Localisation</span><span class="visible-xs">Localisation</span></a></li>
								<li><a href="#reviews">Avis (<?= $ad->meta("num_review")?>)</a></li>
							</ul>
						</div>
						<div class="studio_description">
							<a class="btn btn-purple btn-block visible-xs" href="#contact">Contacter le studio</a>
							<div class="row">
								<div class="studio_description_image">
									<?= $this->imgTag($org->firstImage(), "large-square", array("size"=>"195xauto")) ?>
								</div>
								<div class="studio_description_texte">
							    <?= $org->description() ?>
								</div>
							</div>
							<div class="row studio_description_tag">
								<br>
								<p>STYLES : 
							  	<? foreach($org->attributes("tattoo_style") as $style): ?>
							  	<span class="resultat_content_texte_tag"><?= $style->name() ?></span>
							  	<? endforeach ?>
								</p>
						  	<? $piercings = $org->attributes("piercing_style") ?>
						  	<? if($piercings->count() > 0):?>
						  	<p><?= __("PIERCING")?></h3>
							  	<? foreach($piercings as $style): ?>
							  	<span class="resultat_content_texte_tag"><?= $style->name() ?></span>
							  	<? endforeach ?>
						  	</p>
						  	<? endif ?>
							</div>
							<div class="row studio_description_footer">
						  	<? if($org->tattoobox):?>
									<img src="/tattoome/images/tatoobox.png" alt="">
								<? endif ?>
								<?= $this->link(array(), "creations")->a('CRÉATION : Créez vous-même votre tatouage', "pull-right") ?>
							</div>
						</div>
						<div class="studio_photos" id="photos">
							<a class="btn btn-purple btn-block visible-xs" href="#contact">Contacter le studio</a>
							<h2>Photos</h2>
							<div class="studio_photos_carousel">
								<?= $this->partial("shared/_carousel.phtml", array("images"=>$images,	"size"=>"orig")); ?>
							</div>
						</div>
						<div class="studio_tatoueurs" id="products">
							<a class="btn btn-purple btn-block  visible-xs" href="#contact">Contacter le studio</a>
							<h2>Tatoueurs</h2>
							<!-- Nav tabs -->
							
					  	<ul class="nav nav-tabs" role="tablist">
					  		<? foreach($products as $x=>$r_product):?>
							    <li role="presentation" class="<?= $x == 0 ? 'active':''?>"><a href="#prod-<?= $r_product->id ?>" data-target="#prod-<?= $r_product->id ?>" aria-controls="home" role="tab" data-toggle="tab"><?= $r_product->name() ?></a></li>
							 	<? endforeach?>
					  	</ul>
						  <!-- Tab panes -->
						    <div class="tab-content">
 						  		<? foreach($products as $x=>$r_product):?>
							    <div role="tabpanel" class="tab-pane <?= $x == 0 ? 'active':''?>" id="prod-<?= $r_product->id ?>">
							    	<p><?= $r_product->description() ?> 	  	
							    	<? if($interview_url = $r_product->interview()): ?>
							    		<a target="_blank" href="<?= $interview_url ?>">Lisez son Interview sur le blog</a></p>
							    	<? endif ?>
										<div class="studio_photos_carousel">
									  	<? $images = $r_product->images(); ?>
										  <? if($images->count() > 0): ?>
										    <?= $this->partial("shared/_carousel.phtml", array("images"=>$r_product->images(),	"size"=>"orig")); ?>	  
									  	<? endif ?>
										</div>
							    </div>
							    <? endforeach ?>
						    </div>
						</div>
						<div class="studio_localisation" id="location">
							<a class="btn btn-purple btn-block visible-xs" href="#contact">Contacter le studio</a>
							<h2>Localisation / Horaires</h2>
							<div class="studio_localisation_map">
									<div id="org_gmap" style="background: url(/img/staticmap.png); height:100%; margin-top:15px; text-align:center">
										<button class="btn btn-default" id="show-map" style="margin-top:130px"><?= __("Voir la localisation")?></button>
									</div>
							</div>
							<div class="studio_localisation_info">
								<div class="studio_localisation_adresse">
									<h4>Adresse</h4>
							  	<p><?= $org->name() ?></p>
						  		<p><?= $org->completeAddress("</p><p>") ?></p>
								</div>
								<div class="studio_localisation_horaires">
									<h4>Horaires d'ouverture</h4>
							  	<? 
							  	$days = array();
							  	foreach(json_decode($org->opening_days()) as $data){
								  	$hours = explode("_", $data);
								  	$day = explode("-", $hours[0]);
								  	$days[$day[0]][] = __("de :open: à :close:", array("open"=>$hours[1], "close"=>$hours[2]));
							  	}
							  	?>
							  	<? $date = new Zend_Date() ?>
							  	<? foreach($days as $day=>$times): ?>
 										<div class="horaire_singleton">										
								  	  <p class="left_content"><?= ucfirst($date->set($day+1, Zend_Date::WEEKDAY_8601)->get(Zend_Date::WEEKDAY));?></p>
								  	  <? foreach($times as $time): ?>
								 			<p class="right_content"><?= $time?></p>
								 			<? endforeach ?>
										</div>
							  	<? endforeach; ?>
								</div>
							</div>
						</div>
						<div class="studio_avis" id="reviews">
							<h2>Avis (<?= $ad->meta("num_review")?>)</h2>
							<div class="row">
								<div class="studio_avis_global">
									<div class="row_avis_singleton">
										<p class="left_content avis_left"><b>Note globale, basée sur <?= $ad->meta("num_review")?> avis</b></p>
										<div class="bloc_etoile">
											<?= $this->starRate("moyenne_globale", $ad->avg_rating); ?>
										</div>
									</div>
									<? foreach ($rates = $org->calcReviewCriteriaAverage() as $criteria): ?>  	
								  	<? 
								  		$r_criteria = App::table("attributes")->find($criteria['id'])->current(); 
								  		$label = $r_criteria->name(); 
								  		$method = $r_criteria->key;
								  	?>
					    		<div class="row_avis_singleton">
										<p class="left_content avis_left"><?= $label ?></p>
										<div class="bloc_etoile">
											<?= $this->starRate("rating_global_".$criteria['id'], $criteria['avg']); ?>
										</div>
									</div>
								  <? endforeach ?>
								</div>
								<div class="studio_avis_know">
									<h3>vous connaissez ce studio ?</h3>
									<p>Partagez votre experience avec les autres internautes</p>
									<a href="#">Laissez un avis</a>
								</div>
							</div>
						  <? foreach($this->reviews_data as $review): ?>
						  <?= $this->partial("shared/_review.phtml", array("review"=>$review)); ?>
						  <? endforeach ?>
						  
						  <div class="row">
							  <? $form_review = $this->form_review;
								  $form_review->hideLabels(true);
							  ?>
							  <?= $this->formHeader($form_review, array(
							  	"action"=>"#form-review", 
							  	"class"=>"studio_avis_form")) ?>

								<div class="studio_avis_form" id="form-review">
									<h3>Laissez un avis</h3>
									<div class="studio_avis_form_left_part">
										<div class="studio_avis_global">
											<p class="left_content avis_left"><b>Note par critère</b></p>
											<? foreach ($form_review->getCriteria() as $r_criteria): ?>
											<div class="clearfix">
												<p class="left_content avis_left"><?= $r_criteria->name(); ?></p>
												<div class="bloc_etoile">
													<?= $form_review->renderGroups(array($r_criteria->key)) ?>
												</div>
											</div>
							        <? endforeach; ?>
										</div>
										<?= $form_review->renderGroups(array(
								      "name"=>__("Votre avis en une phrase"),
								      "description"=>array(
								        "label"=>__("Commentaire"),
								        "attribs"=>array("rows"=>3))));?>
						      </div>
									<div class="studio_avis_form_right_part">										
								    <?= $form_review->renderGroups(array(
								      "lname"=>__("Votre nom"),
								      "fname"=>__("Votre prénom"),
								      "email"=>__("Votre adresse email"),
								      "website"=>array("group_class"=>"hide"))) ?>
										<button type="submit" class="custom_submit">Envoyez votre avis</button>
									</div>
								</div>
							</form>
						</div>
					</div>
					</div>
					<!-- fin content -->
					<!-- sidebar -->
					<div class="studio_sidebar_width" id="form_fixed">
						<h2 id="contact">Contactez le studio</h2>
						<p>Par téléphone</p>
					  <a class="phone-number-toggler collapse in bt" 
					  	data-toggle="collapse" 
					  	data-target=".phone-number,.phone-number-toggler">
					  		<?= __("Voir le numéro de téléphone")?>
					  </a>
					  <p class="well well-sm collapse phone-number"><span class="glyphicon glyphicon-phone"></span><?= $org->phoneNumber() ?></p>
						<p>Par email</p>
				  	<? if($contacted = $this->contact_form->sentTo($org->id)): ?>
				  	<div class="alert alert-success alert-dismissable">
						  <?= __("Votre message à bien été envoyé à ce studio. Si vous souhaitez envoyer un autre message, ") ?>
						  <a href="javascript:void()" class="alert-link" data-target="#contact-form-content" data-toggle="collapse">
						  	<?= __("cliquez ici")?>
						  </a>
				  	</div>
				  	<? endif ?>
						<div id="contact-form-content" class="<?= $contacted ? "collapse":""?>">
						  <p><?=__("Pour contacter le studio, remplissez le formulaire suivant")?></p>
						  <?= $this->formHeader($this->contact_form) ?>
						    <? $this->contact_form->hideLabels(true); ?>
						    <?= $this->contact_form->renderGroups(array(
						      "fname"=>__("Nom*"),
						      "lname"=>__("Prénom*"),
						      "email"=>__("E-mail*")
						    ));?>
						    <?= $this->contact_form->renderGroups(array(
						      "message"=>array(
						        "label"=>__("Précisez votre demande*"),
						        "attribs"=>array("rows"=>5))
						    ));?>
								<p class="required_fields">* champs obligatoires</p>
								<button type="submit" class="custom_submit">Envoyer</button>
							</form>
						</div>
					</div>
					<!--fin sidebar -->
				</div>
				<!-- fin content -->
			</div>
		</div>
		<!-- FIN SERP CONTAINER -->
										  <script>
								  //  $(function(){
									      var map = null;
									      var myLatlng = new google.maps.LatLng(<?= $loc->lat ?>,<?= $loc->lng ?>);
												var mapOptions = {
								          zoom: 10,
								          center: myLatlng,
								          mapTypeControl: true,
								          mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU},
								          navigationControl: true,
								          navigationControlOptions: {style: google.maps.NavigationControlStyle.SMALL},
								          mapTypeId: google.maps.MapTypeId.ROADMAP
												}
												var map = new google.maps.Map(document.getElementById("org_gmap"), mapOptions);
												
												var marker = new google.maps.Marker({
												    position: myLatlng,
												});
												
												// To add the marker to the map, call setMap();
												marker.setMap(map);
									      
									 //  });
								  </script>	
