<?
//Preview=true on location page. False on org page.
$review = $this->review['row'];
$response = $this->review['response'];
$review_date = $review->event("new")->zendDate();
$org = $review->Organization();

$desc_split = explode(" ", $review->description(), 20);
if (sizeof($desc_split) > 2) { array_pop($desc_split); }
$desc_preview = implode(" ", $desc_split);


$r_user = $this->user()->loggedUser();
$can_answer = false;
if(isset($r_user)){
	$can_answer = $review->organization()->user_id == $review->organization()->user_id || $r_user->isAdmin();	
}
?>


<div class="row">
	<div class="studio_avis_avis" id="review<?= $review->id ?>">
		<div class="studio_avis_avis_text">
			<p class="author_avis"><?=$review->user()->name()?></p>
			<?= $review->name() ?><br>
			<?= $review->description()->toPara() ?>
			<? if($can_answer && $response instanceOf Uop_Form_ReviewAnswer): ?>
			<?= $this->formHeader($response, array("class"=>"form-answer", "action"=>"#review$review->id"))?>
			<? $response->hideLabels(true) ?>
			<?= $response->renderGroups(array(
	      "description"=>array(
	      	"label"=>__("Votre réponse"),
	      	"attribs"=>array("rows"=>3))));
      ?>
      <button type="submit" class="btn btn-success pull-right btn-xs"><?= __("Répondre") ?></button>
      </form>
			<? elseif($response instanceOf Uop_Model_DbTable_Row_Review): ?>
			<div class="answer">
				<b><?= __("Réponse du Studio:") ?></b>
				<?= $response->description()->toPara() ?>
			</div>
		<? endif ?>
		</div>
		<div class="studio_avis_global">
			<p class="left_content avis_left"><b>Note moyenne</b></p>
			<div class="bloc_etoile">
				<?= $this->starRate("rating_".$review->id, $review->average); ?>
			</div>
			<? foreach (App::table("attributes")->reviewRate() as $r_criteria) : ?>
      <? $method = $r_criteria->key; ?>
			<p class="left_content avis_left"><?= $name = $r_criteria->name();?></p>
			<div class="bloc_etoile">
				<?= $this->starRate("rating_".$review->id."_".$name, $review->$method()); ?>
			</div>
			<? endforeach ?>
		</div>
	</div>
</div>

