<? $this->placeholder('sidebar')->captureStart() ?>
	<h4><?= __("Tatoueurs, rejoignez le réseau!")?></h4>
	<?= $this->link(array(), "subscription-lead")->a("<img src='/img/autopromo.png' class='img-responsive' style='padding-bottom:15px'/>"); ?>
	<h4><?= __("Suivez-nous sur Facebook")?></h4>
	<div class="fb-like-box" data-href="https://www.facebook.com/galeriedutatouage?fref=ts" data-colorscheme="light" data-show-faces="true" data-header="false" data-stream="false" data-show-border="false" data-width="350"
style="background:white"></div>
<? $this->placeholder('sidebar')->captureEnd() ?>
