<div class="serp_promo autopromo" id="serp_promo_1">
	<h2>Création</h2>
	<p>Créez votre tatouage avec un artise dessinateur</p>
	<a href="https://www.galeriedutatouage.com/creation" class="link-promo-red">
		Je crée mon tatouage
	</a>
	</div>
<div class="serp_promo autopromo" id="serp_promo_2">
	<h2>TATTOOBOX</h2>
	<p>Un cadeau inoubliable : offrez un tatouage</p>
	<a href="http://www.galeriedutatouage.com/tattoobox" class="link-promo-lightgreen"> Je choisis ma TATTOOBOX</a>
</div>
<div class="serp_promo_text autopromo">
	<p class="serp_promo_text_label">newsletter</p>
	<h2>news, bons plans, tendances...</h2>
	<p class="serp_promo_text_emphase">Recevez le meilleur du tatouage par email</p>
	<a href="#" class="link-promo-violet"  type="button" data-toggle="modal" data-target="#newsletter">Je m'inscris</a>
</div>

<?= $this->partial("shared/_mailing-dialog.phtml") ?>