<div class="serp_promo" id="serp_promo_1">
	<h2>Création</h2>
	<p>Créez votre tatouage avec un artise dessinateur</p>
	<a href="https://www.galeriedutatouage.com/creation" class="link-promo-red"> Je crée mon tatouage</a>
</div>
<div class="serp_promo" id="serp_promo_2">
	<h2>TATOOBOX</h2>
	<p>Un cadeau inoubliable : offrez un tatouage</p>
	<a href="#" class="link-promo-lightgreen"> Je choisis ma TATOOBOX</a>
</div>
<div class="serp_promo_text">
	<p class="serp_promo_text_label">newsletter</p>
	<h2>news, bons plans, tendances...</h2>
	<p class="serp_promo_text_emphase">Recevez le meilleur du tatouage par email</p>
	<a href="#" class="link-promo-violet">Je m'inscris</a>
</div>
