<?
	$form = $this->form;
	$this->content_with_sidebar = true;
	$bc = $this->breadcrumb()->prepend(Link::home()->a(__("Accueil"))); 
	$bc->append("Espace membre");
?>
<? $this->partial("shared/_sub-header.phtml", $this) ?>

<h1><?= __("Identifiez vous pour accèder à votre espace personel")?></h1>
<div>
<?= $this->formHeader($form); ?>
	<?= $form->renderGroups(array(
		"email"=>__("Adresse email"),
		"password"=>__("Mot de passe")));?>	
<? $footer = $this->formFooter(__("Valider"))->captureStart();?>
<?= $this->link(array(), "user/password-lost")->a("J'ai oublié mon mot de passe...", array("class"=>"pull-left"));?>
<?= $footer->captureEnd() ?>
<?= $this->partial("shared/_remarketing.phtml") ?>
</div>
