<? $this->body_class = "admin-images" ?>

<table class="table table-striped">
    <thead>
        <tr>
            <th style="width: 35%;"><?=__("Image") ?></th>
            <th style="width: 20%;"><?=__("Tatoueurs") ?></th>
            <th style="width: 45%;"><?=__('Légendes') ?></th>
        </tr>
    </thead>
    <? foreach ($this->entities as $row):?>
    <tr>
        <td style="width: 35%;"><img src="<?= $row->url('small') ?>" class="img-thumbnail" style="margin-bottom:40px"/></td>
        <td style="width: 20%;">
            <? if($r_org = $row->organization()): ?>
                <?= $r_org->name() ?>
            <? endif ?>
        </td>
        <td style="width: 45%;">
            <form class="form-image" action="<?=  $this->link(array(), 'updateName')?>">
                <input type="hidden" name="id_image" class="id_image" value="<?= $row->id ?>">
                <input type="text" name="name_image" class="name_image" value="<?= $row->name() ?>" class="form-control" style="width: 80%;float:left;">
                <input type="submit" value="OK" style="width: 15%;margin-top:4px;margin-left:10px;">
            </form>
        </td>
    </tr>
    <? endforeach ?>
</table>
<?= ($this->entities instanceof Zend_Paginator) ? $this->entities : "" ?>
<script>
    $('.form-image').submit(function(e){
       e.preventDefault();
       var id = $(".id_image",this).val();
       var name = $(".name_image",this).val();
       $.ajax({
            type: "POST",
            // DUE TO THE NATURE OF HOW ZEND WORKS YOU NEED ONLY NEED TO PROVIDE /CONTROLLER/ACTION
            url: $(this).attr("action"),
    
             // I USE THIS DATA TYPE WHEN SENDING AJAX REQUESTS IN ZEND
              dataType:  'json',
    
            // YOU DO NOT NEED THE () ONLY {}
            data: { 
                id:id,
                name:name
            },
            cache: false,
            error: function(msg){ 
                alert('Il y a eu une erreur.');
            },
            success: function(){
                alert('Mise à jour effectuée');
            } 
        });      
    });
</script>